# Programa Ingenias+ Data Science

**Notebook 5 trabajado por Loana Ibañez (grupo 7).**

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


**Preparación del entorno de trabajo**

In [5]:
!pip install NumPy

In [7]:
import numpy as np

**1. Crear un arreglo de ceros de longitud 12**

In [8]:
np.zeros((12,), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5**


In [18]:
mi_array2 = np.zeros((10,), dtype=int)
mi_array2[4]= int(10)
print(mi_array2)

[ 0  0  0  0 10  0  0  0  0  0]


**3. Crear un arreglo que tenga los números del 10 al 49**

In [23]:
mi_array3 = np.arange(10, 50, 1, dtype=int)
print(mi_array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8**

In [30]:
mi_array4 = np.arange(9).reshape(3, 3)
print(mi_array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza**

In [40]:
mi_array5 = np.random.randn(100)
print(np.mean(mi_array5))
print(np.var(mi_array5))


-0.04676990230744165
1.1232803202054589


**6. Calcular la media de un arreglo usando np.sum**

In [37]:
print(mi_array3)
print(np.sum(mi_array3)/len(mi_array3)) # esto es igual a print(np.sum(mi_array3))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
29.5


**7. Calcular la varianza de un arreglo usando np.sum y np.mean**

In [36]:
mi_array7 = (1,2,3,4,5,6,7,8,9,10)
varianza = ((np.sum((mi_array7))-np.mean(mi_array7))**2)/len(mi_array7)
print(varianza)

245.025


**8. Crear un array de números aleatorios usando np.random.randn.**

In [29]:
mi_array8 = np.random.randn(10)
print(mi_array8)

[-0.39603578  1.18385345  1.02177731 -0.20709697 -0.62800081 -1.47144396
 -1.99826669  0.47567959  1.02578646 -0.57968312]
